In [ ]:
import pandas as pd

df = pd.read_csv("loan_approval_dataset.csv")

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

df.head()

Dataset loaded successfully!
Dataset shape: (1005, 14)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,EmploymentType,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP100613,Female,Yes,3+,Not Graduate,Yes,Self-Employed,1952.18,2573.76,154.16,120.0,1.0,Urban,Y
1,LP100012,Male,Yes,0,Graduate,Yes,Freelancer,5659.49,0.00,251.94,180.0,0.0,Rural,N
2,LP100225,Male,No,1,Not Graduate,No,Salaried,2999.68,1587.22,109.20,180.0,1.0,Semiurban,Y
3,LP100282,Male,No,1,Graduate,Yes,Business Owner,6265.55,0.00,251.53,360.0,1.0,Semiurban,Y
4,LP100493,Male,No,0,Graduate,Yes,Self-Employed,6942.48,418873.82,267.06,300.0,1.0,Urban,Y

In [ ]:
print("Dataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

Dataset Shape:
(1005, 14)

Column Names:
['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'EmploymentType', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1005 entries, 0 to 1004
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            1005 non-null   object
 1   Gender             955 non-null    object
 2   Married            955 non-null    object
 3   Dependents         955 non-null    object
 4   Education          1005 non-null   object
 5   Self_Employed      955 non-null    object
 6   EmploymentType     1005 non-null   object
 7   ApplicantIncome    1005 non-null   float64
 8   CoapplicantIncome  1005 non-null   float64
 9   LoanAmount         955 non-null    float64
 10  Loan_Amount_Term   955 non-null    float64
 11  Credit_History     955 non-null    float64
 12  Property_Area      1005 non-null   object
 13  Loan_Status        1005 non-null   object
dtypes: float64(5), object(9)
memory usage: 110.1+ KB

Missing Values:
Loan_ID               0
Gender               50
Married              50
Dependents           50
Education             0
Self_Employed        50
EmploymentType        0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           50
Loan_Amount_Term     50
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

Duplicate Rows:
5

In [ ]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 5

In [ ]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Loan_ID               0
Gender               50
Married              50
Dependents           50
Education             0
Self_Employed        50
EmploymentType        0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           50
Loan_Amount_Term     50
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
# Remove duplicate rows
df = df.drop_duplicates()

print("Duplicate rows removed.")
print("New dataset shape:", df.shape)
print("Remaining duplicates:", df.duplicated().sum())

Duplicate rows removed.
New dataset shape: (1000, 14)
Remaining duplicates: 0

In [ ]:
print("Dataset Information:")
print(df.info())

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1005 entries, 0 to 1004
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            1005 non-null   object
 1   Gender             955 non-null    object
 2   Married            955 non-null    object
 3   Dependents         955 non-null    object
 4   Education          1005 non-null   object
 5   Self_Employed      955 non-null    object
 6   EmploymentType     1005 non-null   object
 7   ApplicantIncome    1005 non-null   float64
 8   CoapplicantIncome  1005 non-null   float64
 9   LoanAmount         955 non-null    float64
 10  Loan_Amount_Term   955 non-null    float64
 11  Credit_History     955 non-null    float64
 12  Property_Area      1005 non-null   object
 13  Loan_Status        1005 non-null   object
dtypes: float64(5), object(9)
memory usage: 110.1+ KB
None

In [ ]:
categorical_cols = [
    "Gender",
    "Married",
    "Dependents",
    "Self_Employed"
]

for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

/tmp/ipykernel_2698/1950880874.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].fillna(df[col].mode()[0])

In [ ]:
numerical_cols = [
    "LoanAmount",
    "Loan_Amount_Term",
    "Credit_History"
]

for col in numerical_cols:
    df[col] = df[col].fillna(df[col].median())

/tmp/ipykernel_2698/327900904.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].fillna(df[col].median())

In [ ]:
print("Missing values after handling:")
print(df.isnull().sum())

Missing values after handling:
Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
EmploymentType       0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [ ]:
if "Loan_ID" in df.columns:
    df = df.drop("Loan_ID", axis=1)

print("Loan_ID removed.")
print("Remaining columns:")
print(df.columns.tolist())

Loan_ID removed.
Remaining columns:
['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'EmploymentType', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status']

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoders = {}

categorical_columns = df.select_dtypes(include="object").columns

for col in categorical_columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

print("Categorical columns encoded successfully.")

df.head()

Categorical columns encoded successfully.

,Gender,Married,Dependents,Education,Self_Employed,EmploymentType,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,0,1,3,1,1,3,1952.18,2573.76,154.16,120.0,1.0,2,1
1,1,1,0,0,1,1,5659.49,0.00,251.94,180.0,0.0,0,0
2,1,0,1,1,0,2,2999.68,1587.22,109.20,180.0,1.0,1,1
3,1,0,1,0,1,0,6265.55,0.00,251.53,360.0,1.0,1,1
4,1,0,0,0,1,3,6942.48,418873.82,267.06,300.0,1.0,2,1

In [ ]:
print("Final Dataset Information:")
df.info()

Final Dataset Information:
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 1004
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             1000 non-null   int64
 1   Married            1000 non-null   int64
 2   Dependents         1000 non-null   int64
 3   Education          1000 non-null   int64
 4   Self_Employed      1000 non-null   int64
 5   EmploymentType     1000 non-null   int64
 6   ApplicantIncome    1000 non-null   float64
 7   CoapplicantIncome  1000 non-null   float64
 8   LoanAmount         1000 non-null   float64
 9   Loan_Amount_Term   1000 non-null   float64
 10  Credit_History     1000 non-null   float64
 11  Property_Area      1000 non-null   int64
 12  Loan_Status        1000 non-null   int64
dtypes: float64(5), int64(8)
memory usage: 109.4 KB

In [ ]:
print("Final Dataset:")
display(df.head())

Final Dataset:

,Gender,Married,Dependents,Education,Self_Employed,EmploymentType,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,0,1,3,1,1,3,1952.18,2573.76,154.16,120.0,1.0,2,1
1,1,1,0,0,1,1,5659.49,0.00,251.94,180.0,0.0,0,0
2,1,0,1,1,0,2,2999.68,1587.22,109.20,180.0,1.0,1,1
3,1,0,1,0,1,0,6265.55,0.00,251.53,360.0,1.0,1,1
4,1,0,0,0,1,3,6942.48,418873.82,267.06,300.0,1.0,2,1

In [ ]:
print("Missing values:")
print(df.isnull().sum())

Missing values:
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
EmploymentType       0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [ ]:
X = df.drop("Loan_Status", axis=1)
y = df["Loan_Status"]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (1000, 12)
Target shape: (1000,)

In [ ]:
print("Missing values before handling:")
print(df.isnull().sum())

Missing values before handling:
Loan_ID               0
Gender               50
Married              50
Dependents           50
Education             0
Self_Employed        50
EmploymentType        0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           50
Loan_Amount_Term     50
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (800, 12)
Testing data: (200, 12)

In [ ]:
# Save the preprocessed dataset
df.to_csv("processed_loan_data.csv", index=False)

print("Preprocessed dataset saved successfully!")

Preprocessed dataset saved successfully!

In [ ]:
# Check the saved file
import os

print(os.path.exists("processed_loan_data.csv"))

True